INSERT INTO ENDERECO (ID, BAIRRO, LOGRADOURO, NUMERO) VALUES
(1, 'Copacabana', 'Avenida atlântica', '270'),
(2, 'Ipanema', 'Rua Vinicius de Moraes', '110'),
(3, 'Leblon', 'Avenida Delfim Moreira', '1234'),
(4, 'Barra da Tijuca', 'Avenida das Américas', '2000'),
(5, 'Botafogo', 'Rua Voluntários da Pátria', '400'),
(6, 'Santa Teresa', 'Rua Almirante Alexandrino', '501'),
(7, 'Laranjeiras', 'Rua das Laranjeiras', '1'),
(8, 'Jardim Botânico', 'Rua Jardim Botânico', '1008'),
(9, 'Gávea', 'Rua Marquês de São Vicente', '225'),
(10, 'Flamengo', 'Avenida Rui Barbosa', '762'),
(11, 'Tijuca', 'Rua Conde de Bonfim', '358'),
(12, 'Lapa', 'Rua do Lavradio', '71'),
(13, 'Catete', 'Rua do Catete', '153'),
(14, 'Glória', 'Rua da Glória', '98'),
(15, 'Maracanã', 'Rua Professor Eurico Rabelo', '30'),
(16, 'Centro', 'Avenida Rio Branco', '1'),
(17, 'Santa Cruz', 'Rua Felipe Cardoso', '5000'),
(18, 'Campo Grande', 'Rua Campo Grande', '958'),
(19, 'Rocinha', 'Rua 1', '800'),
(20, 'Jacarepaguá', 'Estrada dos Três Rios', '2000');

INSERT INTO DEMANDA (ID, SITUACAO, ENDERECO_ID, TITULO, DESCRICAO) VALUES
(1,0, 1, 'Buraco na rua', 'Tem um buraco no meio da rua que pode causar um acidente grave'),
(2,0, 2, 'Falta de iluminação', 'As luzes dos postes estão quebradas deixando o local mal iluminado e perigoso'),
(3, 0, 3, 'Vazamento de água', 'Há um vazamento de água na calçada que está desperdiçando recursos e causando alagamento'),
(4, 0, 4, 'Calçada danificada', 'A calçada está quebrada e representa um risco de tropeço para os pedestres'),
(5, 0, 5, 'Árvore caída', 'Uma árvore caiu bloqueando a passagem de veículos e pedestres'),
(6, 0, 6, 'Bueiro entupido', 'O bueiro está entupido e causando alagamento na rua durante as chuvas'),
(7, 0, 7, 'Pichação em prédio público', 'Um prédio público foi pichado, comprometendo a estética e o patrimônio'),
(8, 0, 8, 'Semáforo com defeito', 'O semáforo está com defeito e causando confusão no trânsito'),
(9, 0, 9, 'Falta de coleta de lixo', 'O lixo não está sendo coletado regularmente, causando acúmulo e mau cheiro'),
(10, 0, 10, 'Estacionamento irregular', 'Veículos estão estacionando irregularmente em local proibido'),
(11, 0, 11, 'Infiltração em residência', 'Uma residência está com problemas de infiltração, causando danos à estrutura'),
(12, 0, 12, 'Roubo de placas de rua', 'Placas de rua foram roubadas, dificultando a orientação dos moradores e visitantes'),
(13, 0, 13, 'Falta de sinalização de trânsito', 'Falta de sinalização em cruzamento perigoso está causando acidentes'),
(14, 0, 14, 'Escola com infestação de pragas', 'Uma escola está com infestação de pragas, comprometendo a saúde dos alunos'),
(15, 0, 15, 'Buraco em ciclovia', 'Um buraco na ciclovia está colocando em risco os ciclistas que passam pelo local'),
(16, 0, 16, 'Falta de acessibilidade em calçada', 'A calçada não possui rampa de acessibilidade para cadeirantes'),
(17, 0, 17, 'Poste com fiação exposta', 'Um poste está com a fiação exposta, representando perigo para pedestres'),
(18, 0, 18, 'Depósito irregular de entulho', 'Entulho está sendo depositado irregularmente em via pública'),
(19, 0, 19, 'Invasão de área pública', 'Uma área pública está sendo invadida por moradores irregulares'),
(20, 0, 20, 'Ponto de ônibus danificado', 'O ponto de ônibus está danificado, oferecendo pouco conforto aos passageiros');